### ISSUE TITLE
Crafting recipes don't work without Better Nether

### ISSUE THREAD

**Issue by d4rkm0nkey** [Azagwen/ATBYW#34] opened 2021-06-25 13:57 UTC
I installed this mod together with Better End, but not with Better Nether and I couldn't craft for example the wooden pickaxe out of oak planks and oak_sticks. I got a lot of errors regarding recipes with better nether, so I installed Better Nether and now it works.
Better Nether is not listed as a necessary dependency, so I assume that this is a bug.

**Comment by Azagwen** [comment] 2021-06-25 14:01
What version of the mod are you using ?

**Comment by d4rkm0nkey** [comment] 2021-06-25 14:01
atbyw-1.16.5-1.4.1.jar

**Comment by d4rkm0nkey** [comment] 2021-06-25 14:03
I just realized that there are still some errors:
```
Couldn't load block tag atbyw:bookshelves as it is missing following references: atbyw:better_nether/stalagnate_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_nether/reeds_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_nether/willow_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_nether/wart_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_nether/rubeus_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_nether/mushroom_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_nether/mushroom_fir_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_nether/anchor_tree_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_nether/nether_sakura_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_end/mossy_glowshroom_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_end/pythadendron_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_end/end_lotus_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_end/lacugrove_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_end/dragon_tree_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_end/tenanea_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_end/helix_tree_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_end/umbrella_tree_bookshelf_toggle (from atbyw_mi/mod_interaction_resources)
13:53:36.427
net.minecraft.class_3503
main
Couldn't load item tag atbyw:pistons as it is missing following references: atbyw:spruce_piston (from All The Blocks You Want (ATBYW)),atbyw:birch_piston (from All The Blocks You Want (ATBYW)),atbyw:jungle_piston (from All The Blocks You Want (ATBYW)),atbyw:acacia_piston (from All The Blocks You Want (ATBYW)),atbyw:dark_oak_piston (from All The Blocks You Want (ATBYW)),atbyw:crimson_piston (from All The Blocks You Want (ATBYW)),atbyw:warped_piston (from All The Blocks You Want (ATBYW)),atbyw:spruce_sticky_piston (from All The Blocks You Want (ATBYW)),atbyw:birch_sticky_piston (from All The Blocks You Want (ATBYW)),atbyw:jungle_sticky_piston (from All The Blocks You Want (ATBYW)),atbyw:acacia_sticky_piston (from All The Blocks You Want (ATBYW)),atbyw:dark_oak_sticky_piston (from All The Blocks You Want (ATBYW)),atbyw:crimson_sticky_piston (from All The Blocks You Want (ATBYW)),atbyw:warped_sticky_piston (from All The Blocks You Want (ATBYW))
13:53:36.428
net.minecraft.class_3503
main
Couldn't load item tag atbyw:bookshelves as it is missing following references: atbyw:better_nether/stalagnate_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_nether/reeds_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_nether/willow_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_nether/wart_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_nether/rubeus_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_nether/mushroom_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_nether/mushroom_fir_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_nether/anchor_tree_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_nether/nether_sakura_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_end/mossy_glowshroom_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_end/pythadendron_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_end/end_lotus_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_end/lacugrove_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_end/dragon_tree_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_end/tenanea_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_end/helix_tree_bookshelf_toggle (from atbyw_mi/mod_interaction_resources),atbyw:better_end/umbrella_tree_bookshelf_toggle (from atbyw_mi/mod_interaction_resources)
```

**Comment by Azagwen** [comment] 2021-06-25 14:04
I see, bugs related to sticks and recipes have been removed in 1.17 because I simply got rid of the sitcks I had added, I'll see what I can do, but I'm not a fan of backporting stuff.

Also those errors aren't critical, they're just due to the tags not loading properly because of some experimental or mod interaction blocks missing.

**Comment by d4rkm0nkey** [comment] 2021-06-25 14:06
I can understand the backporting thing, but it would be nice to support at least 1.16.5 at the moment, because most mods are not compatible with 1.17 yet and it will take a while. So modpacks are all still on 1.16.5. And I really like your mod.

**Comment by Azagwen** [comment] 2021-06-25 14:08
I'll try to push a 1.4.2 for 1.16.5 asap then :)

**Comment by d4rkm0nkey** [comment] 2021-06-25 14:09
Nice! Thank you! I mean the mod is working. I am just confused that I had to install Better Nether.

**Comment by Azagwen** [comment] 2021-06-25 14:12
That's odd yeah, but I expect it's related to the stick-involving recipes, which I'll just solve the same way I did in 1.17 I guess, those have been trouble makers for a while now.

**Comment by Azagwen** [comment] 2021-06-26 13:41
A release that should fix this is now out
Feel free to test it and tell me if it works on your end, I will close this issue once this is confirmed

**Comment by Azagwen** [comment] 2021-06-29 04:32
Closing this since no feedback seems to be given

**Closed as completed** 2021-06-29 04:32 UTC
Labels: bug, Mod compatibility, In Release, Waiting for response
